version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    deploy:
      placement:
        constraints: [node.role == worker]
        #constrains:
        #  - node.labels.manager == yes
      #mode: replicated
      #replicas: 2   
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.75'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.5'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      #update_config:
      #  parallelism: 1
      #  delay: 10s
      #  failure_action: continue
      #  monitor: 60s
      #  max_failure_ratio: 0.3

  drupal:
    image: docker.io/bitnami/drupal-nginx:10
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
    deploy:
      placement:
        constraints: [node.role == manager]
        #constrains:
        #  - node.labels.manager == yes
      #mode: replicated
      #replicas: 2      
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      #update_config:
      #  parallelism: 1
      #  delay: 10s
      #  failure_action: continue
      #  monitor: 60s
      #  max_failure_ratio: 0.3
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local

#https://codefresh.io/blog/deploy-docker-compose-v3-swarm-mode-cluster/
